### ISSUE TITLE
🐛 Bug Report:  broken link on "about docsgpt" page

### ISSUE THREAD

**Issue by barkhaaroraa** [arc53/DocsGPT#498] opened 2023-10-07 19:19 UTC
### 📜 Description

on clicking on this, it leads to "No webpage was found for the web address: https://www.arc53.com/docs.html"

### 👟 Reproduction steps

go to the about page, then click on "this link"

### 👍 Expected behavior

it shouldnt lead to the guidelines as intended 

### 👎 Actual Behavior with Screenshots

<img width="818" alt="image" src="https://github.com/arc53/DocsGPT/assets/115429121/06883238-1757-43f6-adf1-f116d97ffebe">
<img width="798" alt="image" src="https://github.com/arc53/DocsGPT/assets/115429121/04e60938-8cf0-4239-97d9-118bf49c2d7a">

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alienishi** [comment] 2023-10-07 20:19
@dartpain I would like to resolve this issue please assign me this issue

**Comment by kelvinparmar** [comment] 2023-10-08 04:33
@dartpain I want to work on this issue please assign to me

**Comment by barkhaaroraa** [comment] 2023-10-08 07:35
@dartpain could you please assign this to me under hacktober fest

**Comment by tenokami** [comment] 2023-10-08 12:06
Assigned to @barkhaaroraa

**Comment by barkhaaroraa** [comment] 2023-10-08 21:02
hi, just a small doubt, where should the link exactly take the user to? https://docs.docsgpt.co.uk/ or some other link?

**Comment by dartpain** [comment] 2023-10-08 22:03
I think link https://docs.docsgpt.co.uk/ this is the best option.
Also I dont need to add labels hacktoberfest to issues or PR's, it will be reflected in your account in any case.

**Comment by JoyelJohny** [comment] 2023-10-11 07:33
@tenokami Can i work on this issue

**Comment by tenokami** [comment] 2023-10-11 07:36
> @tenokami Can i work on this issue

@barkhaaroraa Is already on it

**Comment by tenokami** [comment] 2023-10-11 08:28
@dartpain ^

**Comment by barkhaaroraa** [comment] 2023-10-11 10:19
Yes @JoyelJohny is right, even I noticed the same. The about.tsx doesn’t have the same content as the website. I tried looking for the phases used on that page of the website throughout the repo but didn’t find any file that had those phases. So could you please look into this because I haven’t been able to find the file that contains that broken link…

**Comment by HeetVekariya** [comment] 2023-10-11 12:38
@barkhaaroraa I get it.
- The website on which you have identified the issue is: https://docsgpt.arc53.com (Link available in the README.md, Title = **DocsGPT 🦖 Live**)
- However this repo contains the code for this website: https://docs-gpt-git-main-arc53.vercel.app ( Link not available anywhere i think so, title = **DocsGPT🦖**)

### What to do further:
- @tenokami Please let them know the codebase for the current issue if possible.

Hey, @barkhaaroraa @JoyelJohny can you please help in setting up the code locally for testing (if you have done the set up), because i am not able to get the response for the question when i run the website.(We can connect on discord)

**Comment by tenokami** [comment] 2023-10-11 13:57
@dartpain ^

**Comment by dartpain** [comment] 2023-10-11 20:43
We have an open source version and a cloud demo version. Cloud demo is slightly different and was quite behind the opensource version in terms of updates. When creating issues its best to check the latest version from the repository,

Thank you so much!

**Closed by dartpain** 2023-10-11 20:43 UTC
