### ISSUE TITLE
🐛 Bug Report: react web widget minor issue

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#1283] opened 2024-10-09 09:30 UTC
### 📜 Description

Latest version of react rect web widget prints undefined before printing an answer
https://github.com/arc53/DocsGPT/blob/main/extensions/react-widget/src/components/DocsGPTWidget.tsx

### 👟 Reproduction steps

1. Update inside docs/ folder docsgpt npm module to latest version
2. Spin up nextra website
3. Submit a query to widget

### 👍 Expected behavior

No undefined in the beginning

### 👎 Actual Behavior with Screenshots

![CleanShot 2024-10-09 at 10 29 54@2x](https://github.com/user-attachments/assets/d41feda8-8347-4448-9fcd-9002dacc4f10)

### 💻 Operating system

MacOS

### What browsers are you seeing the problem on?

Chrome

### 🤖 What development environment are you experiencing this bug on?

Local dev server

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

No

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 45hv1n** [comment] 2024-10-09 11:40
Hi @dartpain, 
I would like to work on this could you please assign this to me.

Thank you

**Comment by Ayushjhawar8** [comment] 2024-10-09 13:21
hi can i work on this?

**Comment by Srayash** [comment] 2024-10-20 19:29
The issue may be caused by trying to append data.answer to queries[queries.length - 1].response. If data.answer is initially undefined, this would result in concatenating undefined before an answer.

<img width="679" alt="Screenshot 2024-10-21 at 12 52 50 AM" src="https://github.com/user-attachments/assets/841fd12a-f3cc-4ad8-804b-3f1ba82f8285">

could you assign it to me if it's still open?

**Comment by Srayash** [comment] 2024-10-21 11:00
Hi @ManishMadan2882 ,

I've submitted a PR (#1355) addressing the issue. Could you please review it when you have a chance? Thank you!

**Closed** 2024-10-21 13:42 UTC
Labels: help wanted, javascript, hacktoberfest, extensions
