### ISSUE TITLE
🚀 Feature: adding text to speech to responses

### ISSUE THREAD

**Issue by albinsabu2023** [arc53/DocsGPT#1234] opened 2024-10-04 18:32 UTC
### 🔖 Feature description

Adding a text to speech along with like ,dislike and copy 

### 🎤 Why is this feature needed ?

this will make the user interaction easier .rather than just reading some long paragraphs user can  hear the response as voice to the query 

### ✌️ How do you aim to achieve this?

 # Use the Web Speech API
The Web Speech API provides a speechSynthesis interface to convert text to speech. Here’s how you can integrate it into a React component.

### 🔄️ Additional Information

i have tried and implemented in this my previous projects

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?
yes

**Comment by Vaishnavi-Raykar** [comment] 2024-10-05 04:36
@dartpain 
This is already raised by me #1202 and you assigned it to some other person. Now this person raising same issue again. What's going on ?

**Comment by dartpain** [comment] 2024-10-05 08:37
This is a duplicate of #1202

**Closed by dartpain** 2024-10-05 08:37 UTC
